### ISSUE TITLE
Disconnecting while trying to read in data

### ISSUE THREAD

**Issue by koenderks** [patriciamar/ShinyItemAnalysis#460] opened 2021-04-02 13:22 UTC
Dear maintainer,

First of all, thank you for making this great shiny app! I got it to produce a report of my results once last year, but this time I am unable to read in my data and generate a report (in both HTML and pdf) because the app keeps disconnecting from the server.

Steps to reproduce:

1. Read in the data using the ordinal data type in the options:
[resultsperquestion.zip](https://github.com/patriciamar/ShinyItemAnalysis/files/6249669/resultsperquestion.zip)

![image](https://user-images.githubusercontent.com/25059399/113419151-2bf23280-93c7-11eb-9c64-20a72e30bbf5.png)

Now I believe that this means that an error occurs in the underlying R code but, from this screen, I am unable to deduce what is going wrong. Maybe you can offer some advice in how I can get the report using these data?

**Comment by patriciamar** [comment] 2021-04-02 14:03
Many thanks for reporting and for the reproducibility data. The error seems to be caused by item 3.3 which has all correct answers. Before this issue is fixed in the app, consider removing this item from your data.

**Comment by koenderks** [comment] 2021-04-09 06:38
Hi @patriciamar,

Thank your for looking into this issue so quickly. This has resolved my problems.

Great Shiny app you guys have made!

**Comment by patriciamar** [comment] 2021-06-01 09:31
This issue is now fixed with the new version 1.3.7. No need for removing items. Please reopen the issue if you find any problems. Thanks for reporting and for your positive feedback!

**Closed by patriciamar** 2021-06-01 09:31 UTC
